// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AXXXXClient is the client API for AXXXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AXXXXClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type aXXXXClient struct {
	cc grpc.ClientConnInterface
}

func NewAXXXXClient(cc grpc.ClientConnInterface) AXXXXClient {
	return &aXXXXClient{cc}
}

func (c *aXXXXClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/xx.xxx.AXXXX/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXXXXClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xx.xxx.AXXXX/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AXXXXServer is the server API for AXXXX service.
// All implementations must embed UnimplementedAXXXXServer
// for forward compatibility
type AXXXXServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAXXXXServer()
}

// UnimplementedAXXXXServer must be embedded to have forward compatible implementations.
type UnimplementedAXXXXServer struct {
}

func (UnimplementedAXXXXServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedAXXXXServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedAXXXXServer) mustEmbedUnimplementedAXXXXServer() {}

// UnsafeAXXXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AXXXXServer will
// result in compilation errors.
type UnsafeAXXXXServer interface {
	mustEmbedUnimplementedAXXXXServer()
}

func RegisterAXXXXServer(s grpc.ServiceRegistrar, srv AXXXXServer) {
	s.RegisterService(&AXXXX_ServiceDesc, srv)
}

func _AXXXX_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXXXXServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xx.xxx.AXXXX/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXXXXServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AXXXX_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXXXXServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xx.xxx.AXXXX/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXXXXServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AXXXX_ServiceDesc is the grpc.ServiceDesc for AXXXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AXXXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xx.xxx.AXXXX",
	HandlerType: (*AXXXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _AXXXX_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _AXXXX_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AXXXX.proto",
}
