// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: BBCCXX.proto

package XXXX

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BBCCXXClient is the client API for BBCCXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BBCCXXClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type bBCCXXClient struct {
	cc grpc.ClientConnInterface
}

func NewBBCCXXClient(cc grpc.ClientConnInterface) BBCCXXClient {
	return &bBCCXXClient{cc}
}

func (c *bBCCXXClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/XXXXX.XXXX.BBCCXX/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BBCCXXServer is the server API for BBCCXX service.
// All implementations must embed UnimplementedBBCCXXServer
// for forward compatibility
type BBCCXXServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedBBCCXXServer()
}

// UnimplementedBBCCXXServer must be embedded to have forward compatible implementations.
type UnimplementedBBCCXXServer struct {
}

func (UnimplementedBBCCXXServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedBBCCXXServer) mustEmbedUnimplementedBBCCXXServer() {}

// UnsafeBBCCXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BBCCXXServer will
// result in compilation errors.
type UnsafeBBCCXXServer interface {
	mustEmbedUnimplementedBBCCXXServer()
}

func RegisterBBCCXXServer(s grpc.ServiceRegistrar, srv BBCCXXServer) {
	s.RegisterService(&BBCCXX_ServiceDesc, srv)
}

func _BBCCXX_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBCCXXServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XXXXX.XXXX.BBCCXX/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBCCXXServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BBCCXX_ServiceDesc is the grpc.ServiceDesc for BBCCXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BBCCXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "XXXXX.XXXX.BBCCXX",
	HandlerType: (*BBCCXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _BBCCXX_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BBCCXX.proto",
}
