// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RRXXClient is the client API for RRXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RRXXClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type rRXXClient struct {
	cc grpc.ClientConnInterface
}

func NewRRXXClient(cc grpc.ClientConnInterface) RRXXClient {
	return &rRXXClient{cc}
}

func (c *rRXXClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/xxx.xxx.RRXX/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rRXXClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxx.xxx.RRXX/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RRXXServer is the server API for RRXX service.
// All implementations must embed UnimplementedRRXXServer
// for forward compatibility
type RRXXServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedRRXXServer()
}

// UnimplementedRRXXServer must be embedded to have forward compatible implementations.
type UnimplementedRRXXServer struct {
}

func (UnimplementedRRXXServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedRRXXServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedRRXXServer) mustEmbedUnimplementedRRXXServer() {}

// UnsafeRRXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RRXXServer will
// result in compilation errors.
type UnsafeRRXXServer interface {
	mustEmbedUnimplementedRRXXServer()
}

func RegisterRRXXServer(s grpc.ServiceRegistrar, srv RRXXServer) {
	s.RegisterService(&RRXX_ServiceDesc, srv)
}

func _RRXX_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RRXXServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxx.RRXX/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RRXXServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RRXX_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RRXXServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxx.RRXX/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RRXXServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RRXX_ServiceDesc is the grpc.ServiceDesc for RRXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RRXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxx.xxx.RRXX",
	HandlerType: (*RRXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _RRXX_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _RRXX_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RRXX.proto",
}
