// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package XXX

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TTXXBBClient is the client API for TTXXBB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTXXBBClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type tTXXBBClient struct {
	cc grpc.ClientConnInterface
}

func NewTTXXBBClient(cc grpc.ClientConnInterface) TTXXBBClient {
	return &tTXXBBClient{cc}
}

func (c *tTXXBBClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/XXX.XXX.TTXXBB/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTXXBBClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/XXX.XXX.TTXXBB/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TTXXBBServer is the server API for TTXXBB service.
// All implementations must embed UnimplementedTTXXBBServer
// for forward compatibility
type TTXXBBServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTTXXBBServer()
}

// UnimplementedTTXXBBServer must be embedded to have forward compatible implementations.
type UnimplementedTTXXBBServer struct {
}

func (UnimplementedTTXXBBServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedTTXXBBServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedTTXXBBServer) mustEmbedUnimplementedTTXXBBServer() {}

// UnsafeTTXXBBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTXXBBServer will
// result in compilation errors.
type UnsafeTTXXBBServer interface {
	mustEmbedUnimplementedTTXXBBServer()
}

func RegisterTTXXBBServer(s grpc.ServiceRegistrar, srv TTXXBBServer) {
	s.RegisterService(&TTXXBB_ServiceDesc, srv)
}

func _TTXXBB_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTXXBBServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XXX.XXX.TTXXBB/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTXXBBServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTXXBB_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTXXBBServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XXX.XXX.TTXXBB/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTXXBBServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TTXXBB_ServiceDesc is the grpc.ServiceDesc for TTXXBB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTXXBB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "XXX.XXX.TTXXBB",
	HandlerType: (*TTXXBBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _TTXXBB_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _TTXXBB_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TTXXBB.proto",
}
