// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XXAABBClient is the client API for XXAABB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XXAABBClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xXAABBClient struct {
	cc grpc.ClientConnInterface
}

func NewXXAABBClient(cc grpc.ClientConnInterface) XXAABBClient {
	return &xXAABBClient{cc}
}

func (c *xXAABBClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/xxx.xxx.XXAABB/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xXAABBClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxx.xxx.XXAABB/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXAABBServer is the server API for XXAABB service.
// All implementations must embed UnimplementedXXAABBServer
// for forward compatibility
type XXAABBServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXXAABBServer()
}

// UnimplementedXXAABBServer must be embedded to have forward compatible implementations.
type UnimplementedXXAABBServer struct {
}

func (UnimplementedXXAABBServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedXXAABBServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedXXAABBServer) mustEmbedUnimplementedXXAABBServer() {}

// UnsafeXXAABBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XXAABBServer will
// result in compilation errors.
type UnsafeXXAABBServer interface {
	mustEmbedUnimplementedXXAABBServer()
}

func RegisterXXAABBServer(s grpc.ServiceRegistrar, srv XXAABBServer) {
	s.RegisterService(&XXAABB_ServiceDesc, srv)
}

func _XXAABB_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXAABBServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxx.XXAABB/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXAABBServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XXAABB_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXAABBServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxx.XXAABB/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXAABBServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XXAABB_ServiceDesc is the grpc.ServiceDesc for XXAABB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XXAABB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxx.xxx.XXAABB",
	HandlerType: (*XXAABBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _XXAABB_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _XXAABB_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXAABB.proto",
}
