// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xxxxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BBCCEEEClient is the client API for BBCCEEE service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BBCCEEEClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type bBCCEEEClient struct {
	cc grpc.ClientConnInterface
}

func NewBBCCEEEClient(cc grpc.ClientConnInterface) BBCCEEEClient {
	return &bBCCEEEClient{cc}
}

func (c *bBCCEEEClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/xxx.xxxxx.BBCCEEE/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bBCCEEEClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxx.xxxxx.BBCCEEE/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BBCCEEEServer is the server API for BBCCEEE service.
// All implementations must embed UnimplementedBBCCEEEServer
// for forward compatibility
type BBCCEEEServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedBBCCEEEServer()
}

// UnimplementedBBCCEEEServer must be embedded to have forward compatible implementations.
type UnimplementedBBCCEEEServer struct {
}

func (UnimplementedBBCCEEEServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedBBCCEEEServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedBBCCEEEServer) mustEmbedUnimplementedBBCCEEEServer() {}

// UnsafeBBCCEEEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BBCCEEEServer will
// result in compilation errors.
type UnsafeBBCCEEEServer interface {
	mustEmbedUnimplementedBBCCEEEServer()
}

func RegisterBBCCEEEServer(s grpc.ServiceRegistrar, srv BBCCEEEServer) {
	s.RegisterService(&BBCCEEE_ServiceDesc, srv)
}

func _BBCCEEE_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBCCEEEServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxxxx.BBCCEEE/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBCCEEEServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BBCCEEE_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BBCCEEEServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxxxx.BBCCEEE/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BBCCEEEServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BBCCEEE_ServiceDesc is the grpc.ServiceDesc for BBCCEEE service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BBCCEEE_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxx.xxxxx.BBCCEEE",
	HandlerType: (*BBCCEEEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _BBCCEEE_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _BBCCEEE_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BBCCEEE.proto",
}
